spring.application.name=managementApp
spring.datasource.url=jdbc:mysql://localhost:3306/manage_db
spring.datasource.username=root
spring.datasource.password=Arshad123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
